"""ajuste_logistica_flota

Revision ID: 43e5b5e2f68d
Revises: 
Create Date: 2026-04-18 15:33:56.834639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43e5b5e2f68d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disponibilidad_vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.String(length=50), nullable=False),
    sa.Column('dia_disponible_retorno', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('despachos_regionales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehiculos_asignados', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('costo_unitario_externo', sa.Float(), nullable=True))

    with op.batch_alter_table('disrupciones_empresa', schema=None) as batch_op:
        batch_op.alter_column('datos_extra',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_profs_id', 'simulacion', ['simulacion_id'], ['id'])
        batch_op.create_foreign_key('fk_profs_id', 'usuarios', ['profesor_id'], ['id'])

    with op.batch_alter_table('metricas', schema=None) as batch_op:
        batch_op.alter_column('market_share',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_codigo_estudiante_unique'))
        batch_op.drop_index(batch_op.f('idx_codigo_profesor'), sqlite_where=sa.text('codigo_profesor IS NOT NULL'))
        batch_op.drop_index(batch_op.f('idx_email_unique'))
        batch_op.create_unique_constraint(None, ['codigo_profesor'])
        batch_op.create_foreign_key('fk_profs_id', 'usuarios', ['profesor_id'], ['id'])

    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.alter_column('demanda_mercado_total',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.alter_column('demanda_mercado_total',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('idx_email_unique'), ['email'], unique=1)
        batch_op.create_index(batch_op.f('idx_codigo_profesor'), ['codigo_profesor'], unique=1, sqlite_where=sa.text('codigo_profesor IS NOT NULL'))
        batch_op.create_index(batch_op.f('idx_codigo_estudiante_unique'), ['codigo_estudiante'], unique=1)

    with op.batch_alter_table('metricas', schema=None) as batch_op:
        batch_op.alter_column('market_share',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('disrupciones_empresa', schema=None) as batch_op:
        batch_op.alter_column('datos_extra',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('despachos_regionales', schema=None) as batch_op:
        batch_op.drop_column('costo_unitario_externo')
        batch_op.drop_column('vehiculos_asignados')

    op.drop_table('disponibilidad_vehiculos')
    # ### end Alembic commands ###
